- get_url: url="{{ shibbolethidp_hakacrt }}" dest="{{ shibbolethidp_idp_home }}/credentials/{{ shibbolethidp_hakacrt | basename }}" mode=0755

- xml:
    file: "{{ shibbolethidp_idp_home }}/conf/metadata-providers.xml"
    xpath: /x:MetadataProvider/x:MetadataProvider[@id="HTTPHakaMetadataProvider"]
    namespaces:
      x: "urn:mace:shibboleth:2.0:metadata"
    state: absent

- xml:
    file: "{{ shibbolethidp_idp_home }}/conf/metadata-providers.xml"
    xpath: /x:MetadataProvider
    pretty_print: yes
    namespaces: &namespaces
      x: "urn:mace:shibboleth:2.0:metadata"
      xsi: "http://www.w3.org/2001/XMLSchema-instance"
    add_children:
      - MetadataProvider:
          id: HTTPHakaMetadata
          refreshDelayFactor: "0.5"
          maxRefreshDelay: PT2H
          httpCaching: memory
          "{http://www.w3.org/2001/XMLSchema-instance}type": FileBackedHTTPMetadataProvider
          backingFile: "%{idp.home}/metadata/haka-metadata.xm"
          metadataURL: "https://haka.funet.fi/metadata/haka-metadata.xml"
          _:
            - MetadataFilter:
                "{http://www.w3.org/2001/XMLSchema-instance}type": SignatureValidation
                certificateFile: "%{idp.home}/credentials/{{ shibbolethidp_hakacrt | basename }}"
            - MetadataFilter:
                "{http://www.w3.org/2001/XMLSchema-instance}type": EntityRoleWhiteList
                _:
                  - RetainedRole: md:SPSSODescriptor
