---
- name: create your initial IdP configuration
  shell: docker run -i -v /tmp:/ext-mount --rm cscfi/shibboleth-idp init-idp.sh; cp -r /tmp/customized-shibboleth-idp $(pwd)
  args:
    creates: customized-shibboleth-idp/

- name: Main | Configurables
  include: tags/{{ item }}.yml
  with_items: "{{ tags }}"
  when: tags defined and tags!=""
